### ISSUE TITLE
【plan】2017.10.第三周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#105]
**2017.10.16**
- [x] 禅道 BUG #38443:: 【0.6.0】【bug】【法宝】法宝激活新技能后要重登才能生效 **必须完成**
- [x] 禅道 BUG #38161::【0.6.0】【经验副本】经验副本内的鼓舞和药水功能 **必须完成**
- [x] 【副本】记录玩家进入副本的次数到历史表 #106 **必须完成**
- [x] 禅道 BUG #38406::【0.6.0】【bug】【道具】分男女的装备绑定状态有误 **必须完成**
- [x] 禅道 BUG #38300::【Trunk】【仙盟】仙盟每日福利领取 - 离线时间道具 **必须完成**
-------------------------------------------------------------------------------------------------
**2017.10.17**
- [x] 【技能】将技能cd写进数据库 #107 **必须完成**
- [x] 答题副本选择错误后，离开场景/离开游戏，重新进入场景，客户端收到的状态是错误的，但是设置玩家位置的是在正确的位置  **必须完成**  **需要跟策划确认，玩家重入副本的情况如何处理，再修复** 
- [x] 禅道 BUG #38415::【0.6.0】【功能】【活动】怪物额外掉落包开发 **必须完成**
- [x] 禅道 BUG #38420::【bug】【战斗】组队情况下战斗模式为强制时可以攻击队友 **必须完成** **需要跟策划确认**
-------------------------------------------------------------------------------------------------
**2017.10.18**
- [x] 禅道 BUG #37712::【Trunk】【背包】背包添加“一键出售”功能  **必须完成**
- [x]  活动增加每日累计充值条件 **必须完成**
- [x]  活动增加累计充值条件 **必须完成**
- [x] 禅道 BUG #38219::【0.6.2】【VIP】VIP卡改为只有第一次使用才增加VIP经验 **必须完成**
- [x] 禅道 BUG #38221::【0.6.2】【仙盟boss】仙盟boss有开启时间显示晚上8点-10点 **必须完成**
-------------------------------------------------------------------------------------------------
**2017.10.19**
- [x] 禅道 BUG   #38322::【0.6.2】【BUG】【经验副本】经验副本显示时间级怪物刷新问题 **必须完成**
- [x] 【活动】活动添加过期删除处理 #109 **必须完成**
-------------------------------------------------------------------------------------------------
**2017.10.20**
- [x] 【投资计划】开发 #110 **必须完成**
- [x] 禅道 BUG #38065::【0.6.2】【仙盟】参加仙盟圣兽活动需要增加限制 **必须完成**
- [x] 禅道 BUG   #38204::【0.6.2】【BUG】【世界boss】世界boss的标签刷新时间错误 **必须完成**
- [x] 禅道 BUG   #38383::【0.6.2】【BUG】【世界boss】使用道具增加boss击杀次数有错误 **必须完成**
- [x] 禅道 BUG #38221::【0.6.2】【仙盟boss】仙盟boss有开启时间显示晚上8点-10点 **必须完成**
-------------------------------------------------------------------------------------------------
**2017.10.21**
- [x] 【幻化】开发 #111  **必须完成**
- [x] BUG #38322::【0.6.2】【BUG】【经验副本】经验副本显示时间级怪物刷新问题 **必须完成**
- [x] 禅道 BUG #38495::【0.6.2】【BUG】【多人副本】多人副本进度保存异常问题 **必须完成**
- [x] 禅道 BUG #38438::【bug】【离线时间】离线奖励时间上限错误 **必须完成**
-------------------------------------------------------------------------------------------------
