### ISSUE TITLE
【plan】2017.10.第四周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#113]
**2017.10.23**
- [x] 禅道 BUG #38495::【0.6.2】【BUG】【多人副本】多人副本进度保存异常问题 **必须完成**
- [x] 禅道 BUG #38467::【0.6.2】【优化】【打怪】怪物击杀个数共享 **必须完成**
- [x] 【仙盟】盟主请求列表为空时，没通知去掉小红点 #114 **必须完成**
- [x] 【仙盟】仙盟圣兽开启, 没有通知小红点 #115 **必须完成**
- [x] 【buffer】buffer下线保存 #117 **必须完成**
-------------------------------------------------------------------------------------------------
**2017.10.24**
- [x] 修改lua检查报错 **必须完成**
- [x] 禅道 BUG #38552::【BUG】原地复活服务器和客户端位置不一致 **必须完成**
- [x] 【月卡】开发 #112 **必须完成**
- [x] 【经验加成】vip增加 buffer 配置，经验加成 #118 **必须完成**
-------------------------------------------------------------------------------------------------
**2017.10.25**
- [x] 禅道 BUG #38521::【bug】【经验副本】经验副本结束倒计时期间仍然会打怪 **必须完成**
- [x] 经验副本, 若玩家还有银币鼓舞次数，手动选择到元宝鼓舞一次后，再次切换回银币时，会报次数已到达上限 **确认是否服务器问题**
- [x] 禅道 BUG #38493::【0.6.4】【bug】【战力计算】坐骑战力计算bug **必须完成**
- [x] 禅道 BUG #37558::【0.6.4】【复活】复活界面增加被谁杀死的事件 **必须完成**
- [x] 禅道 BUG  #38098::【Trunk】【VIP】好友以及聊天需要读取玩家实际的VIP展示 **必须完成**
- [x] 禅道 BUG #38383::【0.6.4】【BUG】【世界boss】使用道具增加boss击杀次数有错误 **必须完成**
-------------------------------------------------------------------------------------------------
**2017.10.26**
- [x] 禅道 BUG #37778::【0.6.4】【优化】【背包】背包满时奖励通过邮件发送 **必须完成**
- [x] 禅道 BUG #38589::【0.6.4】【bug】【修仙论道】修仙论道的功能开启等级限制没有生效 **必须完成**
- [x] 禅道 BUG #38587::【bug】【鼓舞】鼓舞的伤害加成前段有显示，但实际上是没有的，打怪的伤害数值没有变化 **必须完成**
- [x] 禅道 BUG #38577::【功能】【公告】新加系统需要公告的内容 **必须完成**
-------------------------------------------------------------------------------------------------
**2017.10.27**
- [ ] 【寻宝】开发 #119 **未完成**
-------------------------------------------------------------------------------------------------
**2017.10.28**
- [x] 【寻宝】开发 #119 **必须完成** **还差全服记录查询**
- [x] 禅道 BUG #38603::【0.6.4】【bug】【日常】日常里“灵域之巅”活动的进度不会增长 **必须完成**
- [x] 禅道 BUG #38591::【bug】【日常】九层妖塔和三域战场没进入成功也加了活跃度 **必须完成**
- [x] 禅道 BUG #38166::【Trunk】【聊天】世界频道聊天发言需要增加等级限制 **必须完成**
- [ ] BUG #38168::【Trunk】【好友】好友功能需要增加等级限制
- [ ] BUG #38557::【功能】【公告】系统公告中链接还未有相应的效果
- [ ] BUG #38533::【优化】【飘字】经验飘字添加加成百分比显示
-------------------------------------------------------------------------------------------------
- [ ] 禅道 BUG #38061::【0.6.4】【战斗】副本增加安全区需求
- [ ] 禅道 BUG #38565::【0.6.4】【优化】【称号】新增一种跟VIP持续时间挂钩的称号时限
-------------------------------------------------------------------------------------------------
- [ ] BUG #38364::【TODO】【功能】【祈福】新增祈福功能
- [ ] 去除 ce_map_copy_oper 协议中世界等级的字段，并修改相关逻辑读取 cellapp_global.world_level
- [ ] 【好友】提示玩家不在线的BUG #108
- [ ]  【好友】删除好友后，好友列表还存在 #98
- [ ] 禅道 BUG #37807::【优化】【组队】未创建队伍时界面按钮显示相关
- [ ]  活动增加按天数累计充值条件
- [ ] 禅道 BUG   #38363::【TODO】【bug】【组队】组队的经验掉落没有按伤害平分
- [ ] 禅道 BUG #38333::【BUG】【通用】参数表的物品下架时间以及战场水晶塔恢复时间不生效了
- [ ] avatar_detail中的first_charge,second_charge,total_charge等统计相关字段统一通过gateway触发db_player_update去更新
- [x] 鼓舞的伤害加成前段有显示，但实际上是没有的，打怪的伤害数值没有变化
- [ ] 累计登录活动开启的时候，已经错过 daily_reset 的玩家当天不会增加进度
- [ ]  【邮件】send_mail优化 #37
- [ ]  【副本】客户端无法得知，增加的经验是否有经验加成 #96
- [ ]  【活动】问题 #94
- [ ]  【代码规范】将 player_reward_limit 改为 reward_limit (修改结构命名和文件名) #78
- [ ]  【代码规范】gwi_player_reward_limit_update 改为只发更新项，而不是整个 table #79
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57
- [ ]  【后台报表】删除玩家物品 #29 
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血 【delay】
- [ ]  【副本】去除 block_map, 将require block_map的代码改为 require map #85 【delay】
