### ISSUE TITLE
【plan】2017.10.第五周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#121]
**2017.10.30**
- [x] 修改lua报错
- [x] BUG #38168::【Trunk】【好友】好友功能需要增加等级限制
- [ ] BUG #38557::【功能】【公告】系统公告中链接还未有相应的效果 (加了部份(包括策划配置),等客户端确认)
- [x] 【好友】提示玩家不在线的BUG #108
- [x]  【好友】删除好友后，好友列表还存在 #98
- [x]  【后台报表】删除玩家物品 #29 
-------------------------------------------------------------------------------------------------
**2017.10.31**
- [x] 【境界】开发 #122
- [x] 禅道 BUG #38634::【0.6.4】【BUG】【主界面】主界面图标，开服活动类活动不需要显示活动倒计时
- [x] 禅道 BUG #38632::【0.6.4】【bug】【复活】被杀死的情况下离线后，再次上线弹出的复活界面没有显示被什么人击杀
-------------------------------------------------------------------------------------------------
**2017.11.01**
- [x] 禅道 BUG #38389::【0.6.6】【功能】【道具】增加副本次数的道具使用效果开发
- [x] 禅道 BUG #37682::【0.6.6】【BUG】【好友】推荐好友需要增加过滤 
- [x] 禅道 BUG 【0.6.4】【bug】【修仙论道】修仙论道结果显示需要显示玩家名字
- [x] 【0.6.4】【bug】【日常】组队击杀了BOSS只有1人计算了进度
-------------------------------------------------------------------------------------------------
**2017.11.02**
- [x] 修改lua报错
- [x] 禅道 BUG #38660::【0.6.4】【bug】【离线时间】离线时间超过20小时有bug
- [x] 禅道 BUG #38519::【0.6.4】【功能】【修仙论道】修仙论道增加排行榜奖励
-------------------------------------------------------------------------------------------------
**2017.11.03**
- [x] 禅道 BUG #38525::【0.6.4】【功能】【充值】充值界面增加绑元礼包出售
- [x] daily_reward_time 没记录到数据库 #124
- [x] 玩家不在线充值时的邮件 title 和 content
- [x] 禅道 BUG #38636::【0.6.4】【bug】【剑魂】没有解锁的剑魂类型依然可以通过箱子获得
- [x] 禅道 BUG #38666::【0.6.4】【BUG】【邮件】现在没有收到灵域之巅和剑灵塔的每日结算奖励的邮件
- [ ] 【圣灵】开发 #123
- [ ] 禅道 BUG #38609::【0.6.6】【优化】【多人副本】多人副本的飘字提示优化
- [ ] 禅道 BUG #37622::【0.6.6】【技能】范围类技能寻找目标规则修改
- [ ] 禅道 BUG #38556::【0.6.6】【bug】技能错误，怪物死后蓄力技能仍会继续蓄力
- [ ] 仙盟晚宴开发
- [ ] 禅道 BUG #38455::【bug】【buff】buff图标会不消失和buff的倒计时错误
- [ ] 禅道 BUG #38390::【功能】【道具】道具使用条件开发
- [ ] 去除 ce_map_copy_oper 协议中世界等级的字段，并修改相关逻辑读取 cellapp_global.world_level
- [ ] avatar_detail中的first_charge,second_charge,total_charge等统计相关字段统一通过gateway触发db_player_update去更新
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57 
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
- [ ] BUG #38364::【TODO】【功能】【祈福】新增祈福功能
- [ ] 禅道 BUG #37807::【优化】【组队】未创建队伍时界面按钮显示相关
- [ ]  活动增加按天数累计充值条件
- [ ] 禅道 BUG   #38363::【TODO】【bug】【组队】组队的经验掉落没有按伤害平分
- [ ] 禅道 BUG #38333::【BUG】【通用】参数表的物品下架时间以及战场水晶塔恢复时间不生效了
- [ ] 累计登录活动开启的时候，已经错过 daily_reset 的玩家当天不会增加进度
- [ ]  【邮件】send_mail优化 #37
- [ ]  【副本】客户端无法得知，增加的经验是否有经验加成 #96
- [ ]  【活动】问题 #94
- [ ]  【代码规范】将 player_reward_limit 改为 reward_limit (修改结构命名和文件名) #78
- [ ]  【代码规范】gwi_player_reward_limit_update 改为只发更新项，而不是整个 table #79
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血 【delay】
- [ ]  【副本】去除 block_map, 将require block_map的代码改为 require map #85 【delay】
