### ISSUE TITLE
2017.11.第一周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#125]
**2017.11.06**
- [x] 【圣灵】开发 #123
- [x] 禅道 BUG #38677::【0.6.6】【BUG】【VIP】VIP过期后依然可以购买副本次数
---------------------------------------------------------------------------------------------------------
**2017.11.07**
- [x]  圣灵添加 cl_player_holy_ghost_update 通知客户端变更
- [ ] 【天灵夺宝】开发 #126 **未完成**
---------------------------------------------------------------------------------------------------------
**2017.11.08**
- [x] 【天灵夺宝】开发 #126 **未完成**
- [x] 禅道 BUG #38689::【0.6.6】【BUG】【投资计划】投资第一档次后再投资高档次的时候元宝多扣了，应该减去第一档次的元宝
- [x] 禅道 BUG #38705::【0.6.6】【bug】【充值】绑元礼包一购买就会发两封邮件
- [x] 禅道 BUG #38711::【0.6.6】【bug】【活动】月卡的投资立返不应该会错过
- [x] 禅道 BUG #38683::【0.6.6】【bug】【日常】完成仙盟任务后的日常活跃飘字有误
---------------------------------------------------------------------------------------------------------
**2017.11.09**
- [x] 禅道 BUG #38609::【0.6.6】【优化】【多人副本】多人副本的飘字提示优化
- [x] BUG #38727::【0.6.6】【bug】【VIP】VIP等级达到了但是进不去魂殿 
- [x] 禅道 BUG #38735::【0.6.6】【bug】【VIP】VIP过期相关bug
- [x] BUG #38098::【0.6.6】【VIP】好友以及聊天需要读取玩家实际的VIP展示
---------------------------------------------------------------------------------------------------------
**2017.11.10**
- [x] 禅道 BUG #38730::【0.6.6】【优化】【离线奖励】玩家上线获得离线奖励时背包不足则通过邮件发送奖励
- [x] 禅道 BUG #38661::【0.6.6】【BUG】【副本】副本最后的退出副本时间会计入副本挑战时间
- [x] 禅道 BUG #38749::【0.6.6】【bug】【VIP】VIP过期后经验加成buff没有及时消失
- [x] 禅道 BUG #38735::【0.6.6】【bug】【VIP】VIP过期相关bug
- [x] 禅道 BUG #38752::【0.6.6】【BUG】【批量使用】现在批量使用多个物品只有一个物品的效果
- [x] 禅道 BUG #38556::【0.6.6】【bug】技能错误，怪物死后蓄力技能仍会继续蓄力
- [x] 禅道 BUG #38267::【0.6.6】【礼包】新增打开礼包后的展示界面
- [x] 禅道 BUG #38743::【0.6.6】【功能】【境界】玩家境界提升时触发公告
- [x] 禅道 BUG #38731::【0.6.6】【bug】【圣灵】圣灵过期的提醒还没做
- [x] 禅道 BUG #38720::【0.6.6】【bug】【圣灵】圣灵还不能隐藏
