### ISSUE TITLE
2017.11.第2周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#128]
**2017.11.13**
- [x] 【签到】开发 #127
- [ ] 【成就】开发
---------------------------------------------------------------------------------------------------------
**2017.11.14**
- [ ] 【成就】开发
---------------------------------------------------------------------------------------------------------
**2017.11.15**
- [ ] 【成就】开发
- [ ] 【天灵竞技】开发 #130
---------------------------------------------------------------------------------------------------------
**2017.11.16**
- [ ] 【天灵竞技】开发 #130
- [ ] 禅道 BUG #38770::【0.6.8】【bug】【充值】绑元礼包在没购买时就显示“已购买”
- [ ] 禅道 BUG #38764::【0.6.8】【bug】【道具】物品表的level字段不生效
- [ ] 禅道 BUG #38647::【0.6.8】【优化】【世界等级】世界等级加成增加左上角buff显示
- [ ] 禅道 BUG #38732::【0.6.8】【优化】【灵域之巅】希望灵域之巅随机到的最后一名挑战者必定比自己的排名低
- [ ] 禅道 BUG #38360::【0.6.8】【功能】【喇叭】增加玩家发送喇叭功能
- [ ] 禅道 BUG #38390::【0.6.8】【功能】【道具】道具使用条件开发
- [ ] 禅道 BUG #38272::【0.6.8】【竞技场】竞技场挑战目标会随机到自己，应该筛选掉自己
- [ ] 禅道 BUG #38262::【0.6.8】【副本】副本掉落展示优化（结算奖励相关）
- [ ] 禅道 BUG #38778::【0.6.8】【bug】【经验副本】经验副本怪物等级问题
- [ ] 禅道 BUG #38782::【0.6.8】【BUG】【九层妖塔】现在九层妖塔进入下层时没有删除上一层的怪物
---------------------------------------------------------------------------------------------------------
**2017.11.16**
- [ ] 禅道 BUG #38687::【0.6.8】【BUG】【活动】有三个活动奖励未领取时需要通过邮件补发奖励
- [ ] 禅道 BUG #38740::【0.6.8】【GM指令】服务器GM指令限制
- [ ] 禅道 BUG #37945::【0.6.8】【世界boss】剑冢相关
- [ ] 禅道 BUG #38759::【0.6.8】【优化】【技能】非怪物技能也要支持伤害延迟
- [ ] 禅道 BUG #38755::【0.6.8】【优化】被封账号不能在游戏排行榜显示
- [ ] 禅道 BUG #38767::【0.6.8】【功能】【合成】新增合成功能
---------------------------------------------------------------------------------------------------------
- [ ] 禅道 BUG #38737::【bug】【剑魂】剑魂背包上限错误，和背包满后的处理错误
- [ ] 禅道 BUG #38455::【bug】【buff】buff图标会不消失和buff的倒计时错误
- [ ] 禅道 BUG #38596::【BUG】【匹配】自动匹配达到队伍人数上限之后执行进入副本操作，流程有误
- [ ] 禅道 BUG #38563::【BUG】【组队】队伍中当队长离线后，没有自动把队长转移给在线队员
---------------------------------------------------------------------------------------------------------
- [ ] 禅道 BUG #38455::【bug】【buff】buff图标会不消失和buff的倒计时错误
- [ ] 禅道 BUG #38737::【bug】【剑魂】剑魂背包上限错误，和背包满后的处理错误
- [ ] 服务器捡物品奖励优化
- [ ] 禅道 BUG #38687::【0.6.6】【BUG】【活动】有三个活动奖励未领取时需要通过邮件补发奖励
- [ ] 增加世界BOSS击杀记录历史表
- [ ] 仙盟晚宴开发
- [ ] 禅道 BUG #38455::【bug】【buff】buff图标会不消失和buff的倒计时错误
- [ ] 禅道 BUG #38390::【功能】【道具】道具使用条件开发
- [ ] 去除 ce_map_copy_oper 协议中世界等级的字段，并修改相关逻辑读取 cellapp_global.world_level
- [ ] avatar_detail中的first_charge,second_charge,total_charge等统计相关字段统一通过gateway触发db_player_update去更新
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57 
- [ ] BUG #38364::【TODO】【功能】【祈福】新增祈福功能
- [ ] 禅道 BUG #37807::【优化】【组队】未创建队伍时界面按钮显示相关
- [ ]  活动增加按天数累计充值条件
- [ ] 禅道 BUG   #38363::【TODO】【bug】【组队】组队的经验掉落没有按伤害平分
- [ ] 禅道 BUG #38333::【BUG】【通用】参数表的物品下架时间以及战场水晶塔恢复时间不生效了
- [ ] 累计登录活动开启的时候，已经错过 daily_reset 的玩家当天不会增加进度
- [ ]  【邮件】send_mail优化 #37
- [ ]  【副本】客户端无法得知，增加的经验是否有经验加成 #96
- [ ]  【活动】问题 #94
- [ ]  【代码规范】将 player_reward_limit 改为 reward_limit (修改结构命名和文件名) #78
- [ ]  【代码规范】gwi_player_reward_limit_update 改为只发更新项，而不是整个 table #79
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血 【delay】
- [ ]  【副本】去除 block_map, 将require block_map的代码改为 require map #85 【delay】
