### ISSUE TITLE
0.6.8.buglist

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#131]
- [ ] BUG #38744::【0.6.8】【部署】服务器部署
- [ ] BUG #38755::【0.6.8】【优化】被封账号不能在游戏排行榜显示
- [ ] BUG #38824::【0.6.8】【bug】【副本掉落】任务副本怪物配置的掉落不生效
- [ ] BUG #38828::【0.6.8】【BUG】【深渊密卷】使用2个深渊密卷道具会增加了4次经验本次数
- [ ] BUG #38834::【0.6.8】【bug】【死亡】死亡后复活buff列表所有buff全部没有了
- [ ] BUG #38844::【0.6.8】【bug】【日常】玩家击杀首领没有计算到日常次数上
- [ ] BUG #38740::【0.6.8】【GM指令】服务器GM指令限制
------------------------------------------------------------------------------------------------------------
- [ ] BUG #38849::【0.6.8】【功能】【天灵竞技】天灵竞技系统的公告以及成就功能添加
- [ ] BUG #38262::【0.6.8】【副本】副本掉落展示优化（结算奖励相关）
- [ ] BUG #38778::【0.6.8】【bug】【经验副本】经验副本怪物等级问题
- [ ] BUG #38647::【0.6.8】【优化】【世界等级】世界等级加成增加左上角buff显示
- [ ] BUG #38732::【0.6.8】【优化】【灵域之巅】希望灵域之巅随机到的最后一名挑战者必定比自己的排名低
- [ ] BUG #38759::【0.6.8】【优化】【技能】非怪物技能也要支持伤害延迟
------------------------------------------------------------------------------------------------------------

**Comment by kinbei** [comment]
- [ ] BUG #38958::【0.6.10】【公司内测】【bug】【签到】新服第一天签到提示已领取
- [ ] BUG #38906::【0.6.10】【优化】成就系统调用优化
- [ ] BUG #38993::【0.6.10】【公司内测】【bug】【背包】背包整理后绑定和非绑定道具会整合到一起
- [ ] BUG #38985::【0.6.10】【公司内测】【bug】【世界boss】世界boss被击杀后概率直接消失

**Comment by kinbei** [comment]
难重现 bug list
- [ ] BUG #38892::【0.6.10】【BUG】cellapp 有内存泄露
- [ ] BUG #38982::【0.6.10】【公司内测】【bug】【怪物】大漠关口的怪物不打人
- [ ] BUG #37689::【Trunk】【技能】给目标释放增加眩晕buff时会导致目标一直眩晕
