### ISSUE TITLE
2017.11.第3周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#133]
**2017.11.20**
- [x] 禅道 BUG #38871::【0.6.8】【功能】【日常】限时活动添加“天灵竞技” (客户端问题)
- [x] 禅道 BUG #38848::【0.6.8.2】【BUG】【好友】添加好友界面【换一批】没有重新随机一次推荐好友
- [x] 禅道 BUG #38859::【0.6.8.2】【bug】【世界boss】066版本世界boss击杀记录有没显示名字的
- [x] 禅道 BUG #38647::【0.6.8】【优化】【世界等级】世界等级加成增加左上角buff显示(客户端跟进)
- [x] 禅道 BUG #38732::【0.6.8】【优化】【灵域之巅】希望灵域之巅随机到的最后一名挑战者必定比自己的排名低
- [x] 禅道 BUG #38759::【0.6.8】【优化】【技能】非怪物技能也要支持伤害延迟
- [x] 禅道 BUG #38875::【0.6.8.2】【成就】剑魂相关成就补充 
-----------------------------------------------------------------------------------------------------------------
**2017.11.21**
- [x] 禅道 BUG #38866::【0.6.8.2】【成就】灵域之巅相关成就补充
- [x] 禅道 BUG #38867::【0.6.8.2】【成就】寻宝相关成就补充 
- [x] 禅道 BUG #38868::【0.6.8.2】【成就】首领相关成就补充
- [x] 禅道 BUG #38874::【0.6.8.2】【成就】青云夺宝相关成就补充 
- [x] 禅道 BUG #38864::【0.6.8.2】【成就】装备相关成就补充
- [x] 禅道 BUG #38865::【0.6.8.2】【成就】仙盟心法相关成就补充
- [x] BUG #38737::【0.6.8.2】【bug】【剑魂】剑魂背包上限错误，和背包满后的处理错误
- [x] BUG #38798::【0.6.8.2】【BUG】【寻宝】寻宝取出物品导致物品一系列不正常
-----------------------------------------------------------------------------------------------------------------
**2017.11.22**
- [x] BUG #38737::【0.6.8.2】【bug】【剑魂】剑魂背包上限错误，和背包满后的处理错误
- [x] BUG #38907::【0.6.8.2】【bug】【装备】装备强化报错
- [x] BUG #38596::【0.6.8.2】【BUG】【匹配】自动匹配达到队伍人数上限之后执行进入副本操作，流程有误
-----------------------------------------------------------------------------------------------------------------
**2017.11.23**
- [x] BUG #38893::【bug】【资源找回】隔天开启的限时活动在资源找回中没有出现 **必须完成**
-----------------------------------------------------------------------------------------------------------------
**2017.11.24**
- [ ] BUG #38577::【0.6.8.2】【功能】【公告】新加系统需要公告的内容 **必须完成**
- [x] BUG #38737::【0.6.8.2】【bug】【剑魂】剑魂背包上限错误，和背包满后的处理错误 **必须完成**
- [x] BUG #38917::【0.6.8.2】【bug】【合成】当材料数量超过一格堆叠上限时，点击一键合成问题 **必须完成**
- [x] BUG #38839::【0.6.8.2】【bug】【世界boss】世界boss下魂殿标签下场景击杀的boss **必须完成**
- [x] BUG #38740::【0.6.8】【GM指令】服务器GM指令限制 **必须完成**
-----------------------------------------------------------------------------------------------------------------
**2017.11.25**
- [x] BUG #38869::【0.6.8.2】【优化】【离线挂机】离线挂机增加经验加成的计算 **必须完成**
- [ ] BUG #38714::【0.6.8.2】【功能】【世界boss】世界BOSS复活CD **必须完成**
-----------------------------------------------------------------------------------------------------------------
- [ ] BUG #38577::【0.6.8.2】【功能】【公告】新加系统需要公告的内容 **必须完成**
- [ ] BUG #38714::【0.6.8.2】【功能】【世界boss】世界BOSS复活CD **必须完成**
-----------------------------------------------------------------------------------------------------------------
- [ ] BUG #38272::【0.6.10】【竞技场】竞技场挑战目标会随机到自己，应该筛选掉自己
- [ ] BUG #38360::【0.6.10】【功能】【喇叭】增加玩家发送喇叭功能
- [ ] BUG #38883::【0.6.10】【功能】【成就】天灵竞技连胜成就补充
- [ ] BUG #38453::【0.6.10】【功能】【buff】新增一个免疫指定buff类型的效果
- [ ] BUG #38512::【0.6.10】【优化】【商店】增加动态商店
- [ ] BUG #38452::【0.6.10】【bug】【属性配置】移动速度百分比的配置没有生效
- [ ] BUG #38840::【0.6.10】【bug】【寻仙访友】任务进度显示异常 (先找出原因后转交给我)
- [ ] BUG #38796::【0.6.10】【bug】【世界boss】世界boss没有攻击仇恨最高的玩家
-----------------------------------------------------------------------------------------------------------------
- [ ] BUG #38453::【0.6.10】【功能】【buff】新增一个免疫指定buff类型的效果
- [ ] 禅道 BUG #38262::【0.6.8】【副本】副本掉落展示优化（结算奖励相关）
- [ ] 禅道 BUG #38782::【0.6.8】【BUG】【九层妖塔】现在九层妖塔进入下层时没有删除上一层的怪物
- [ ] 禅道 BUG #37945::【0.6.8】【世界boss】剑冢相关
- [ ] 禅道 BUG #38455::【bug】【buff】buff图标会不消失和buff的倒计时错误
- [ ] 禅道 BUG #38563::【BUG】【组队】队伍中当队长离线后，没有自动把队长转移给在线队员
- [ ] 增加世界BOSS击杀记录历史表
- [ ] 仙盟晚宴开发
- [ ] 去除 ce_map_copy_oper 协议中世界等级的字段，并修改相关逻辑读取 cellapp_global.world_level
- [ ] avatar_detail中的first_charge,second_charge,total_charge等统计相关字段统一通过gateway触发db_player_update去更新
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57 
- [ ] BUG #38364::【TODO】【功能】【祈福】新增祈福功能
- [ ] 禅道 BUG #37807::【优化】【组队】未创建队伍时界面按钮显示相关
- [ ]  活动增加按天数累计充值条件
- [ ] 禅道 BUG   #38363::【TODO】【bug】【组队】组队的经验掉落没有按伤害平分
- [ ] 禅道 BUG #38333::【BUG】【通用】参数表的物品下架时间以及战场水晶塔恢复时间不生效了
- [ ] 累计登录活动开启的时候，已经错过 daily_reset 的玩家当天不会增加进度
- [ ]  【邮件】send_mail优化 #37
- [ ]  【副本】客户端无法得知，增加的经验是否有经验加成 #96
- [ ]  【活动】问题 #94
- [ ]  【代码规范】将 player_reward_limit 改为 reward_limit (修改结构命名和文件名) #78
- [ ]  【代码规范】gwi_player_reward_limit_update 改为只发更新项，而不是整个 table #79
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血 【delay】
- [ ]  【副本】去除 block_map, 将require block_map的代码改为 require map #85 【delay】

**Comment by kinbei** [comment]
~~this~~
