### ISSUE TITLE
2017.11.第4周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#137]
2017.11.27
-----------------------------------------------------------------------------------------------------------------
- [x] BUG #38577::【0.6.8.2】【功能】【公告】新加系统需要公告的内容 **必须完成**
- [x] BUG #38714::【0.6.8.2】【功能】【世界boss】世界BOSS复活CD **必须完成**
- [x] BUG #38883::【0.6.10】【功能】【成就】天灵竞技连胜成就补充 **必须完成**
- [x] BUG #38840::【0.6.10】【bug】【寻仙访友】任务进度显示异常 **必须完成**
-----------------------------------------------------------------------------------------------------------------
2017.11.28
- [x] BUG #38918::【0.6.10】【bug】【时装】绑定的时装奖励获得后都变成非绑定的了
- [x] BUG #38934::【0.6.10】【优化】【经验副本】经验副本不需要限制掉落等级 **服务器不需要修改**
- [x] BUG #38796::【0.6.10】【bug】【世界boss】世界boss没有攻击仇恨最高的玩家 **必须完成**
- [x] BUG #38452::【0.6.10】【bug】【属性配置】移动速度百分比的配置没有生效 **必须完成**
- [x] BUG #38360::【0.6.10】【功能】【喇叭】增加玩家发送喇叭功能 **必须完成** 等客户端修改
- [x] BUG #38272::【0.6.10】【竞技场】竞技场挑战目标会随机到自己，应该筛选掉自己 **必须完成**
- [x] BUG #38938::【0.6.10】【bug】【成就】列表显示相关bug
- [x] BUG #38909::【0.6.10】【BUG】【活动】需要限制护送美女过程中无法参加天灵竞技匹配
-----------------------------------------------------------------------------------------------------------------
2017.11.29
- [x] BUG #38453::【0.6.10】【功能】【buff】新增一个免疫指定buff类型的效果 **必须完成**
- [x] BUG #38953::【0.6.10】【bug】【世界boss】世界boss脱战错误 **必须完成**
- [x] BUG #38990::【0.6.10】【公司内测】【bug】【世界等级】世界等级要重新登录才会更新 **必须完成**
- [x] BUG #38988::【0.6.10】【公司内测】【bug】【排行榜】剑灵塔排行榜玩家战力数据没有正常显示 **必须完成**
- [x] BUG #38964::【0.6.10】【公司内测】【bug】【成就】镶嵌宝石的成就有bug **必须完成**
- [x] BUG #38991::【0.6.10】【功能】【活动】投资计划和累计充值增加功能开启限制 **必须完成**
-----------------------------------------------------------------------------------------------------------------
2017.11.30
- [x] BUG #38883::【0.6.10】【功能】【成就】天灵竞技连胜成就补充
- [x] BUG #38979::【0.6.10】【公司内测】【bug】【仙盟】仙盟仓库内的道具有问题
- [x] BUG #38984::【0.6.10】【公司内测】【bug】【公告】公告链接没有做功能等级限制
-----------------------------------------------------------------------------------------------------------------
2017.12.01
- [x] BUG #38996::【0.6.10】【公司内测】【bug】【每日结算】公司内测第二天收到了多封灵域之巅的结算邮件
- [x] BUG #38997::【0.6.10】【公司内测】【bug】【竞技场】现在竞技场可以随机出两个相同的挑战者
- [x] BUG #38974::【0.6.10】【公司内测】【bug】【市场】市场部分分页下的物品没有显示出来以及其他相关bug
- [x] BUG #39006::【0.6.10】【bug】【排行榜】翅膀，法宝，神兵排行，职业不分
- [x] BUG #38989::【0.6.10】【公司内测】【bug】【组队】在同一副地图会显示队员是远离状态
- [x] 经验没有记录到历史表
- [x] BUG #39004::【0.6.10】【公司内测】【bug】【等级】好友列表处等级没有即时刷新刷新
-----------------------------------------------------------------------------------------------------------------
2017.12.02
- [x] BUG #38455::【0.6.10】【bug】【buff】buff图标会不消失和buff的倒计时错误
- [ ] BUG #39020::【0.6.10】【公司内测】【bug】【市场】市场购买物品之后有概率会消失不见
- [x] BUG #39025::【0.6.10】【公司内测】【bug】【资源找回】第三天了，未在资源找回界面中看见有可找回的活动
- [x] BUG #38453::【0.6.10】【功能】【buff】新增一个免疫指定buff类型的效果
- [ ] BUG #37807::【0.6.10】【优化】【组队】未创建队伍时界面按钮显示相关
-----------------------------------------------------------------------------------------------------------------

- [ ] BUG #38962::【0.7.0】【优化】【公告】有玩家开启首充特惠宝箱时增加全服公告

- [ ] BUG #38512::【0.6.10】【优化】【商店】增加动态商店
- [ ] 禅道 BUG #38262::【0.6.8】【副本】副本掉落展示优化（结算奖励相关）
- [ ] 禅道 BUG #38782::【0.6.8】【BUG】【九层妖塔】现在九层妖塔进入下层时没有删除上一层的怪物
- [ ] 禅道 BUG #37945::【0.6.8】【世界boss】剑冢相关
- [ ] 禅道 BUG #38455::【bug】【buff】buff图标会不消失和buff的倒计时错误
- [ ] 禅道 BUG #38563::【BUG】【组队】队伍中当队长离线后，没有自动把队长转移给在线队员
- [ ] 增加世界BOSS击杀记录历史表
- [ ] 仙盟晚宴开发
- [ ] 去除 ce_map_copy_oper 协议中世界等级的字段，并修改相关逻辑读取 cellapp_global.world_level
- [ ] avatar_detail中的first_charge,second_charge,total_charge等统计相关字段统一通过gateway触发db_player_update去更新
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57 
- [ ] BUG #38364::【TODO】【功能】【祈福】新增祈福功能
- [ ] 禅道 BUG #37807::【优化】【组队】未创建队伍时界面按钮显示相关
- [ ]  活动增加按天数累计充值条件
- [ ] 禅道 BUG   #38363::【TODO】【bug】【组队】组队的经验掉落没有按伤害平分
- [ ] 禅道 BUG #38333::【BUG】【通用】参数表的物品下架时间以及战场水晶塔恢复时间不生效了
- [ ] 累计登录活动开启的时候，已经错过 daily_reset 的玩家当天不会增加进度
- [ ]  【邮件】send_mail优化 #37
- [ ]  【副本】客户端无法得知，增加的经验是否有经验加成 #96
- [ ]  【活动】问题 #94
- [ ]  【代码规范】将 player_reward_limit 改为 reward_limit (修改结构命名和文件名) #78
- [ ]  【代码规范】gwi_player_reward_limit_update 改为只发更新项，而不是整个 table #79
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血 【delay】
- [ ]  【副本】去除 block_map, 将require block_map的代码改为 require map #85 【delay】
