### ISSUE TITLE
2017.12.第一周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#140]
2017.12.02
- [ ] BUG #39020::【0.6.10】【公司内测】【bug】【市场】市场购买物品之后有概率会消失不见
- [ ] BUG #38970::【0.6.10】【公司内测】【bug】【世界boss】魂殿标签下的boss没有击杀记录和掉落的道具没有掉落记录
- [ ] BUG #38916::【0.6.10】【功能】【活动】开服冲榜活动开发
- [ ] BUG #38930::【0.6.10】【活动】【新增】野外刷怪经验双倍和每日在线时长奖励
-----------------------------------------------------------------------------------------------------------------
- [ ] BUG #37807::【0.6.10】【优化】【组队】未创建队伍时界面按钮显示相关
- [ ] BUG #38962::【0.7.0】【优化】【公告】有玩家开启首充特惠宝箱时增加全服公告
- [ ] BUG #38512::【0.6.10】【优化】【商店】增加动态商店
- [ ] 禅道 BUG #38262::【0.6.8】【副本】副本掉落展示优化（结算奖励相关）
- [ ] 禅道 BUG #38782::【0.6.8】【BUG】【九层妖塔】现在九层妖塔进入下层时没有删除上一层的怪物
- [ ] 禅道 BUG #37945::【0.6.8】【世界boss】剑冢相关
- [ ] 禅道 BUG #38455::【bug】【buff】buff图标会不消失和buff的倒计时错误
- [ ] 禅道 BUG #38563::【BUG】【组队】队伍中当队长离线后，没有自动把队长转移给在线队员
- [ ] 增加世界BOSS击杀记录历史表
- [ ] 仙盟晚宴开发
- [ ] 去除 ce_map_copy_oper 协议中世界等级的字段，并修改相关逻辑读取 cellapp_global.world_level
- [ ] avatar_detail中的first_charge,second_charge,total_charge等统计相关字段统一通过gateway触发db_player_update去更新
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57 
- [ ] BUG #38364::【TODO】【功能】【祈福】新增祈福功能
- [ ] 禅道 BUG #37807::【优化】【组队】未创建队伍时界面按钮显示相关
- [ ]  活动增加按天数累计充值条件
- [ ] 禅道 BUG   #38363::【TODO】【bug】【组队】组队的经验掉落没有按伤害平分
- [ ] 禅道 BUG #38333::【BUG】【通用】参数表的物品下架时间以及战场水晶塔恢复时间不生效了
- [ ] 累计登录活动开启的时候，已经错过 daily_reset 的玩家当天不会增加进度
- [ ]  【邮件】send_mail优化 #37
- [ ]  【副本】客户端无法得知，增加的经验是否有经验加成 #96
- [ ]  【活动】问题 #94
- [ ]  【代码规范】将 player_reward_limit 改为 reward_limit (修改结构命名和文件名) #78
- [ ]  【代码规范】gwi_player_reward_limit_update 改为只发更新项，而不是整个 table #79
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血 【delay】
- [ ]  【副本】去除 block_map, 将require block_map的代码改为 require map #85 【delay】
