### ISSUE TITLE
2017.12.第3周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#144]
**2017.12.21**
- [x] BUG #39227::【0.7.0】【优化】将天灵夺宝的飘图和公告的逻辑移到 globalmgr 里
- [x] BUG #39166::【0.7.0】【功能】【成就】祈福相关成就开发
- [x] BUG #39151::【0.7.0】【外网测试】【bug】【资源找回】资源找回问题
- [x] 仙盟篝火开发

**2017.12.22**
**2017.12.23**
- [x] 仙盟篝火开发
