### ISSUE TITLE
2017.12.第4周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#145]
**2017.12.25**
- [ ] BUG #39165::【0.7.2】【功能】【红名】新增在和平地图击杀其他玩家，增加一个红名buff机制 **必须完成**
- [ ] BUG #39171::【0.7.2】【外网测试】【bug】【活动】宠物排行榜先满级的玩家被后满级的玩家超越 **必须完成**
- [ ] BUG #39178::【0.7.2】【外网测试】【bug】【世界boss】boss攻击目标会出现不攻击仇恨最高的玩家 **必须完成**
- [ ] BUG #39252::【0.7.0.1】【BUG】【仙盟副本】在仙盟副本中退出仙盟后再点击副本的退出按钮会报错 **必须完成**
