### ISSUE TITLE
【plan】2017.08.14 (8月第三周)

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#3]
_From @kinbei on August 13, 2017 17:41_

**2017.08.14**
- [x] 【队伍】队伍自动匹配增加玩家等级过滤 #995 **修改**
- [x] 【队伍】需要相同的组队目标才可以匹配到一个队伍，目前是无差别匹配 #996 **修改**

_Copied from original issue: kinbei/hero#1008_

**Comment by kinbei** [comment]
**2017.08.18**

- [ ]   怪物在仇恨目标死亡后不会攻击其他人
- [ ]    查看其他玩家信息界面开发 #1010 **详细**

**Comment by kinbei** [comment]
剩余工作

- [ ] 【副本】副本次数在玩家下线重新登录后，没有限制到 #5
- [ ]   怪物在仇恨目标死亡后不会攻击其他人
- [ ]   查看其他玩家信息界面开发 #1010 **详细**

**Comment by kinbei** [comment]
剩余工作

- [ ] 【副本】副本次数在玩家下线重新登录后，没有限制到 #5
- [ ]   怪物在仇恨目标死亡后不会攻击其他人
- [ ]   查看其他玩家信息界面开发 #1010 **详细**
