### ISSUE TITLE
【plan】2017.08.28.第五周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#33]
**2017.08.28**

- [x]  【仙盟仓库】表 tb_guild_sword_soul_pd 改为 tb_guild_sword_soul #31
- [x]   查看其他玩家信息界面开发 #1010 **详细** **未完成**

**Comment by kinbei** [comment]
**2017.08.29**


- [ ]  【副本】副本限制次数类型修改 #30
- [ ]  【仙盟】退仙盟没有清除贡献 #28
- [ ]  【剑灵塔】剑灵塔每日奖励邮件优化 #34
- [ ]  【邮件】新增邮件时，如果超过邮件数上限，那么删除旧的邮件。 #35
- [ ]  【三域战场】战场水晶柱相关问题 #20
- [ ]  【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]  【修仙论道】玩家技能问题 #23
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【后台报表】删除玩家物品 #29
- [ ]  【坐骑】坐骑技能没有生效 #24

**Comment by kinbei** [comment]
**2017.08.30**

- [ ]  【邮件】新增邮件时，如果超过邮件数上限，那么删除旧的邮件。 #35 **未完成**
- [ ]  【三域战场】战场水晶柱相关问题 #20
- [ ]  【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]  【修仙论道】玩家技能问题 #23
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ]  【后台报表】删除玩家物品 #29
- [ ]  【坐骑】坐骑技能没有生效 #24

**Comment by kinbei** [comment]
**2017.08.31**
- [ ]  【坐骑】坐骑技能没有生效 #24  **未完成**
- [ ]  【战力】创角后进入游戏不要飘战力提升 #41
- [ ]  【仙盟】参加仙盟圣兽活动需要增加限制 #42
- [ ]  【三域战场】战场水晶柱相关问题 #20
- [ ]  【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]  【修仙论道】玩家技能问题 #23
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ]  【后台报表】删除玩家物品 #29

**Comment by kinbei** [comment]
**2017.09.01**

- [ ]  【战斗力】玩家登录返回增加称号和仙盟心法信息 #47
- [ ]  【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]  【修仙论道】玩家技能问题 #23
- [ ]  【装备】更换为另一个装备后，“当前血量”会大于“血量上限” #46
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ]  【后台报表】删除玩家物品 #29

**Comment by kinbei** [comment]
**2017.09.02**

- [ ]  【装备】更换为另一个装备后，“当前血量”会大于“血量上限” #46
- [ ]  【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]  【修仙论道】玩家技能问题 #23
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血
- [ ]  【后台报表】删除玩家物品 #29
