### ISSUE TITLE
【plan】2017.09.04.第一周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#54]
**2017.09.04**

- [x]  【排行榜】开发 #53 
- [x]  【排行榜】增加爬塔通关时间 #56
- [x]  【掉落】个人掉落限制问题修改 #55

**Comment by kinbei** [comment]
**2017.09.05**

- [ ]  【掉落】GBM_REG_CELLAPP 协议返回加上 daily_reset_time #58
- [ ]  【掉落】增加拾取判断 #59
- [ ]  【装备】更换为另一个装备后，“当前血量”会大于“血量上限” #46
- [ ]  【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]  【修仙论道】玩家技能问题 #23
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血
- [ ]  【后台报表】删除玩家物品 #29

**Comment by kinbei** [comment]
**2017.09.06**

- [ ]  【掉落】增加拾取判断 #59
- [ ]  【装备】更换为另一个装备后，“当前血量”会大于“血量上限” #46
- [ ]  【三域战场】三域战场原地复活后，别人看到还是在出生点复活
- [ ]  【修仙论道】玩家技能问题 #23
- [ ]  【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血
- [ ]  【后台报表】删除玩家物品 #29

**Comment by kinbei** [comment]
**2017.09.07**
【奖励】修改 get_bulk_reward_cost() 的实现 #66

**Comment by kinbei** [comment]
**2017.09.08**

- [ ]  【资源找回】开发 (2) #69
- [ ]  【资源找回】开发 (3) #70
- [ ]  【三域战场】三域战场原地复活后，别人看到还是在出生点复活
- [ ]  【剑魂】装备防具生命加成的剑魂和基础生命加成的剑魂血量计算不正常 #68
- [ ]  【修仙论道】玩家技能问题 #23
- [ ]  【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血
- [ ]  【后台报表】删除玩家物品 #29

**Comment by kinbei** [comment]
**2017.09.09**

- [ ]  【剑魂】装备防具生命加成的剑魂和基础生命加成的剑魂血量计算不正常 #68
- [ ]  【修仙论道】玩家技能问题 #23
- [ ]  【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血
- [ ]  【后台报表】删除玩家物品 #29
