### ISSUE TITLE
【plan】2017.09.11.第二周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#74]
**2017.09.11**

- [x]   common\netimpl\common\reward_table.lua 需要改为 server\lua\server_common\reward_func.lua 中的 get_bulk_reward_cost() 的形式一样
- [x]  【代码规范】server_common.reward_serial 修改为按类型进行处理 #72
- [x]  【副本】个人副本报错 #73
- [x]  【资源找回】修改 #75
- [x]  【修仙论道】玩家技能问题 #23
- [x]  【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22

**Comment by kinbei** [comment]
- [ ]  【资源找回】资源找回需要加多一个vip可以购买的总次数返回给客户端 #77
- [ ]  【代码规范】将 player_reward_limit 改为 reward_limit (修改结构命名和文件名) #78
- [ ]  【代码规范】gwi_player_reward_limit_update 改为只发更新项，而不是整个 table #79
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血
- [ ]  【后台报表】删除玩家物品 #29

**Comment by kinbei** [comment]
**2017.09.14**

- [ ]  【资源找回】资源找回需要加多一个vip可以购买的总次数返回给客户端 #77
- [ ]  【代码规范】将 player_reward_limit 改为 reward_limit (修改结构命名和文件名) #78
- [ ]  【代码规范】gwi_player_reward_limit_update 改为只发更新项，而不是整个 table #79
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血
- [ ]  【后台报表】删除玩家物品 #29
