### ISSUE TITLE
【plan】2017.08.21.第四周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#8]

**Comment by kinbei** [comment]
**2017.08.21**
- [ ]  穿戴称号实现

**Comment by kinbei** [comment]
**2017.08.22**

- [ ] 【副本】副本次数在玩家下线重新登录后，没有限制到 #5
- [ ]   怪物在仇恨目标死亡后不会攻击其他人
- [ ]   查看其他玩家信息界面开发 #1010 **详细**

**Comment by kinbei** [comment]
**2017.08.23**

**Comment by kinbei** [comment]
**2017.08.24**

- [ ]   【三域战场】战场水晶柱相关问题 #20
- [ ]   【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]   【修仙论道】玩家技能问题 #23
- [ ]   【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]   【坐骑】坐骑技能没有生效 #24

**Comment by kinbei** [comment]
**2017.08.25**
- [ ]  【仙盟仓库】开发 #27 **未完成**
- [ ]   查看其他玩家信息界面开发 #1010 **详细** **未完成**
- [ ]   【三域战场】战场水晶柱相关问题 #20
- [ ]   【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]   【修仙论道】玩家技能问题 #23
- [ ]   【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]   【坐骑】坐骑技能没有生效 #24

**Comment by kinbei** [comment]
**2017.08.26**

**Comment by kinbei** [comment]
本周剩余工作

- [ ]   查看其他玩家信息界面开发 #1010 **详细** **未完成**
- [ ]   【仙盟】退仙盟没有清除贡献 #28
- [ ]   【三域战场】战场水晶柱相关问题 #20
- [ ]   【修仙论道】混乱，踢人两个技能增加冷却时间判断 #22
- [ ]   【修仙论道】玩家技能问题 #23
- [ ]   【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]   【后台报表】删除玩家物品 #29
- [ ]   【坐骑】坐骑技能没有生效 #24 
- [ ]  【副本】副本限制次数类型修改 #30
