### ISSUE TITLE
【plan】2017.09.18.第三周

### ISSUE THREAD

**Issue by kinbei** [kinbei/yjly#81]
- [x]  【市场】开发 #76 **未完成**
- [x]  【奖励】新增成长系统吞噬经验 #82
- [x]  【离线奖励】离线奖励的道具奖励错误 #83
- [ ]  【聊天公告】系统频道以及走马灯需求 #84
- [ ]  【副本】装备本奖励逻辑修改 #86
- [ ]  【副本】去除 block_map, 将require block_map的代码改为 require map #85
- [ ]  【奖励】tb_hist_moneyoper 表的 oper_type 为0 #80
- [ ]  【代码规范】将 player_reward_limit 改为 reward_limit (修改结构命名和文件名) #78
- [ ]  【代码规范】gwi_player_reward_limit_update 改为只发更新项，而不是整个 table #79
- [ ]  【仙盟BOSS】仙盟圣兽boss死亡的时候需要给所有在场景中的玩家奖励帮派贡献 #21
- [ ]  【代码规范】将daily_reset和 weekly_reset 整合到 gbmcronjob 里 #43
- [ ]  【邮件】send_mail优化 #37
- [ ] 【GM】增加一个可以秒全地图怪的GM指令 #38
- [ ] 【代码规范】整合协议GBM_QUERY_GW_DATA 和 GBM_REG_GATEWAY #57
- [ ]  【三域战场】变换怪物阵营时，如果与目标阵营一致，不删怪，只回血
- [ ]  【后台报表】删除玩家物品 #29
